version: "3.9"

services:
  server:
    build:
      context: ./server
    ports:
      - "12345:12345"
    container_name: world_clock_server
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "5000:5000"
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    container_name: world_clock_client
    depends_on:
      - server
    restart: always
