version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "12345:12345"
    restart: unless-stopped
    container_name: world_clock_server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: world_clock_client
    environment:
      DISPLAY: ${DISPLAY}  # Để hỗ trợ GUI (nếu dùng client GUI)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Kết nối X11 GUI
