version: '3.12'

services:
  server:
    build:
      context: ./server
    ports:
      - "12345:12345"
    container_name: server-container

  client:
    build:
      context: ./client
    depends_on:
      - server
    container_name: client-container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix