# Sử dụng base image Python
FROM python:3.10-slim

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép file client.py vào container
COPY client.py .

# Cài đặt các thư viện cần thiết
RUN pip install tkinter requests tkcalendar pytz

# Mở terminal khi container chạy
CMD ["tail", "-f", "/dev/null"]
