# File: Dockerfile.client
FROM python:3.10-slim

# Cài đặt các phụ thuộc
RUN pip install tkinter

# Tạo thư mục làm việc
WORKDIR /app

# Copy mã nguồn
COPY client.py /app

# Khởi động client
CMD ["python", "client.py"]
