# File: Dockerfile.server
FROM python:3.10-slim

# Cài đặt các phụ thuộc
RUN pip install pytz

# Tạo thư mục làm việc
WORKDIR /app

# Copy mã nguồn
COPY server.py /app

# Khởi động server
CMD ["python", "server.py"]
