version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "12345:12345"
    container_name: world_clock_server

  client:
    build:
      context: ./client
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    container_name: world_clock_client
