name: Clock Project Workflow

on:
  push:
    branches: [main]

jobs:
  clock_operations:
    runs-on: ubuntu-latest
    steps:
      - name: Set current time
        run: echo "CURRENT_TIME=$(date +%Y-%m-%dT%H:%M:%S)" >> $GITHUB_ENV

      - name: Display clock project message
        run: echo "Clock Project Workflow started at ${{ env.CURRENT_TIME }}"

      - name: Job success
        if: success()
        run: echo "The Clock Project Workflow completed successfully at ${{ env.CURRENT_TIME }}!"
